<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>ch.bger</groupId>
	<artifactId>alpano</artifactId>
	<version>1.0.0-SNAPSHOT</version>

	<name>alpano</name>
	<url>https://mamie.one</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>

		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-base -->
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-controls -->
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-graphics -->
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-swing -->
		<javafx.version>21.0.2</javafx.version>
		<!-- https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
		<junit.version>5.10.2</junit.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-clean-plugin -->
		<maven-clean.version>3.3.2</maven-clean.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-resources-plugin -->
		<maven-resources.version>3.3.1</maven-resources.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
		<maven-compiler.version>3.13.0</maven-compiler.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin -->
		<maven-surefire.version>3.2.5</maven-surefire.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-jar-plugin -->
		<maven-jar.version>3.3.0</maven-jar.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-install-plugin -->
		<maven-install.version>3.1.1</maven-install.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-deploy-plugin -->
		<maven-deploy.version>3.1.1</maven-deploy.version>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-site-plugin -->
		<maven-site.version>3.12.1</maven-site.version>
		<!--
		https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-project-info-reports-plugin -->
		<maven-project-info.version>3.5.0</maven-project-info.version>
		<!-- https://mvnrepository.com/artifact/org.openjfx/javafx-maven-plugin -->
		<javafx-maven.version>0.0.8</javafx-maven.version>
		<!-- https://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin -->
		<jacoco.version>0.8.11</jacoco.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-base</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-swing</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-clean-plugin</artifactId>
				<version>${maven-clean.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven-resources.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven-surefire.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<version>${maven-jar.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-install-plugin</artifactId>
				<version>${maven-install.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>${maven-deploy.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-site-plugin</artifactId>
				<version>${maven-site.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>${maven-project-info.version}</version>
			</plugin>
			<plugin>
				<groupId>org.openjfx</groupId>
				<artifactId>javafx-maven-plugin</artifactId>
				<version>${javafx-maven.version}</version>
				<configuration>
					<mainClass>ch.epfl.alpano.gui.Alpano</mainClass>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${jacoco.version}</version>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>